version: 2.1

ruby_image: &ruby_image cimg/ruby:3.1.2

parameters:
  yarn_cache_path:
    type: string
    default: "~/.cache/yarn"
  node_modules_cache_path:
    type: string
    default: "~/Libra/node_modules"
  ruby_version:
    type: string
    default: "3.1.2"

executors:
  ruby:
    docker:
      - image: *ruby_image
  rails:
    docker:
      - image: *ruby_image
        environment:
          BUNDLE_PATH: /vendor/bundle
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: root
          DB_PASSWORD: "123456"
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: "123456"
  node:
    docker:
      - image: node:16.17.1

jobs:
  backend-build:
    executor:
      name: rails
    working_directory: ~/Libra
    steps:
      - checkout
      - restore_cache:
          keys:
            - libra-rails-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
            - libra-rails-bundle-{{ checksum ".ruby-version" }}
      - run: bundle install
      - save_cache:
          key: libra-rails-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: set up db
          command: bundle exec rails db:create db:migrate --trace
  backend-rspec-job:
    executor:
      name: rails
    steps:
      - checkout
      - run: bundle --path vendor/bundle
      - run:
          name: run rspec
          command: bundle exec rspec --fail-fast -- $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  frontend-build:
    executor: node
    working_directory: ~/Libra
    steps:
      - checkout
      - restore_cache:
          keys:
            - libra-cache-node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - libra-cache-yarn-v1.22.5-{{ checksum "yarn.lock" }}
      - run:
          command: |
            yarn install \
              --frozen-lockfile \
              --cache-folder << pipeline.parameters.yarn_cache_path >>
      - save_cache:
          key: libra-cache-yarn-v1.22.5-{{ checksum "yarn.lock" }}
          paths:
            - << pipeline.parameters.yarn_cache_path >>
      - save_cache:
          key: libra-cache-node-modules-{{ checksum "yarn.lock" }}
          paths:
            - << pipeline.parameters.node_modules_cache_path >>
  front-test-job:
    executor: node
    working_directory: ~/Libra
    steps:
      - checkout
      - restore_cache:
          keys:
            - libra-cache-node-modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - libra-cache-yarn-v1.22.5-{{ checksum "yarn.lock" }}
      - run:
          command: yarn ciTest

workflows:
  backend-rspec:
    jobs:
      - backend-build
      - backend-rspec-job:
          requires:
            - backend-build
  frontend-unit-test:
    jobs:
      - frontend-build
      - front-test-job:
          requires:
            - frontend-build
